function err = E(theta,numberOfGaussians,parametersDimension,numberOfSamplesTraining ...
                            ,numberOfSamplesTrueDensity,trueDensitySamples,MMDtrueDensitySamples,kernelSigmaSquare)

  [weights,means,sigmas] = mcmcParamToRealParam(theta,numberOfGaussians,parametersDimension);
  
  samples = twoModeSurrogateMultipleEvaluation ...
              ( getSamplesFromGaussians(weights,means,sigmas,numberOfGaussians,parametersDimension,numberOfSamplesTraining) );


  err     = MMDtrueDensitySamples ...
            + ( sum( exp( (-(samples.' - samples).^2) / (2*kernelSigmaSquare) ) , 'all') - numberOfSamplesTraining ) ...
                                                         / ( numberOfSamplesTraining*(numberOfSamplesTraining-1) )   ...
            - ( 2*sum( exp( (-(samples.' - trueDensitySamples).^2) / (2*kernelSigmaSquare) ) , 'all') ) ...
                                                         / ( numberOfSamplesTraining*numberOfSamplesTrueDensity ) ;
  err = abs(err);

end

